# Generated by Django 4.2.6 on 2023-10-08 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pacientes',
            old_name='raza',
            new_name='raza_json',
        ),
    ]
