# Generated by Django 4.2.6 on 2023-10-09 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_raza_pacientes_raza_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='raza_json',
            field=models.TextField(max_length=300),
        ),
    ]
