# Generated by Django 4.2.6 on 2023-10-09 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_pacientes_raza_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ficha_clinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alergias', models.CharField(max_length=120)),
                ('antecedentes', models.CharField(max_length=250)),
                ('sintomas_clinicos', models.CharField(max_length=150)),
                ('piel_y_mucosa', models.CharField(max_length=100)),
                ('temperatura_historica', models.FloatField()),
                ('frecuencia_cardiaca', models.IntegerField()),
                ('respiracion', models.CharField(max_length=100)),
                ('dieta_tipo', models.CharField(max_length=100)),
                ('medio_ambiente', models.CharField(max_length=100)),
                ('medicamentos', models.CharField(max_length=100)),
                ('otras_mascotas', models.CharField(max_length=150)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='pacientes',
            name='raza_json',
        ),
        migrations.AddField(
            model_name='pacientes',
            name='caracter',
            field=models.CharField(default='Maquiavelico', max_length=100),
        ),
        migrations.AddField(
            model_name='pacientes',
            name='especie',
            field=models.CharField(default='Perro', max_length=150),
        ),
        migrations.AddField(
            model_name='pacientes',
            name='nacimiento',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='pacientes',
            name='observacion',
            field=models.TextField(default='Sin observaciones'),
        ),
        migrations.AddField(
            model_name='pacientes',
            name='pelaje',
            field=models.CharField(default='Peludo', max_length=50),
        ),
        migrations.AddField(
            model_name='pacientes',
            name='peso',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='pacientes',
            name='raza',
            field=models.TextField(default='Sharpei'),
        ),
        migrations.AddField(
            model_name='pacientes',
            name='servicios',
            field=models.CharField(default='Atencion Clinica', max_length=300),
        ),
        migrations.AddField(
            model_name='pacientes',
            name='sexo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='ruc_ci',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='telefono',
            field=models.IntegerField(),
        ),
    ]
