# Generated by Django 4.2.6 on 2023-10-09 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_ficha_clinica_remove_pacientes_raza_json_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='nacimiento',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='sexo',
            field=models.BooleanField(default=True),
        ),
    ]
